#!/bin/bash

# these are the settings for the computers I'm using at the moment

exp=$2
iter=$3
mkdir base/${exp}

if [ $1 = bria ] #briareos
then
    port=16384
    url=0.tcp.ngrok.io
    path=/home/guillefix/code/
elif [ $1 = lbria ] #local briareos
then
    port=22
    url=192.168.1.103
    path=~/code/
elif [ $1 = hydra ] #hydra
then
    port=22
    url=$hydra
    path=/users/guillefix/
elif [ $1 = gcloud ] #google cloud
then
    gcloud compute scp --project skillful-eon-241416 --zone us-central1-a --recurse tensorflow-1-vm:~/code/beatsaber/base/${exp}/opt.json base/${exp}
    gcloud compute scp --project skillful-eon-241416 --zone us-central1-a --recurse tensorflow-1-vm:~/code/beatsaber/base/${exp}/iter_${iter}_net_.pth base/${exp}
    exit 0
fi
scp -P $port ${url}:${path}beatsaber/base/${exp}/opt.json base/${exp}
scp -P $port ${url}:${path}beatsaber/base/${exp}/iter_${iter}_net_.pth base/${exp}
