#!/bin/bash

export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/"

py=python3
dataset=general_full_state_look_ahead
model=adv_wavenet
layers=7
blocks=3
exp=chroma_features_likelihood_gan_exp

$py train.py --data_dir=../AugData --dataset_name=$dataset --model=$model --batch_size=1 --output_length=32 --num_windows=10 --nepoch=500 --nepoch_decay=500 --layers=$layers --blocks=$blocks --print_freq=10 --experiment_name=$exp --save_by_iter --save_latest_freq=1000 \
    --dilation_channels=512 \
    --residual_channels=256 \
    --skip_channels=256 \
    --end_channels=512 \
    --gpu_ids=0,1,2,3,4,5,6,7 \
    --entropy_loss_coeff=0.3 \
    --workers=8
    #--load \
    #--load_iter=1000 \
