#!/bin/bash

export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/"

py=python3
dataset=general_beat_saber
model=transformer
exp=transformer_testing

$py train.py --data_dir=../AugDataTest --dataset_name=$dataset --model=$model --batch_size=2 --num_windows=0 --nepoch=500 --nepoch_decay=500 --print_freq=10 --experiment_name=$exp --save_by_iter --save_latest_freq=1000 \
    --pad_batches \
    --label_smoothing \
    --max_token_seq_len=500 \
    --reduced_state \
    --using_sync_features \
    --gpu_ids=0 \
    --level_diff=Expert\
    --workers=0
    #--load \
    #--load_iter=1000 \
