#!/bin/bash

#export PYTHONPATH="/home_directory/.local/lib/python3.5/site-packages/"

py=python3
dataset=general_beat_saber
model=wavenet
layers=7
blocks=3
exp=chroma_features_likelihood_syncc
num_windows=10

$py train.py --data_dir=../AugData --dataset_name=$dataset --model=$model --batch_size=1 --output_length=32 --num_windows=$num_windows --nepoch=500 --nepoch_decay=500 --layers=$layers --blocks=$blocks --print_freq=10 --experiment_name=$exp --save_by_iter --save_latest_freq=5000 \
    --time_shifts=16 \
    --input_channels=$((24*16+2004)) \
    --num_classes=$((2004)) \
    --extra_output \
    --dilation_channels=512 \
    --residual_channels=256 \
    --skip_channels=256 \
    --end_channels=512 \
    --entropy_loss_coeff=0.0 \
    --workers=0 \
    --level_diff=Expert \
    --reduced_state \
    --concat_outputs \
    --gpu_ids=0 \
    #--load \
    #--load_iter=70000 \
